name: mini_games
description: "Flutter mini games."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  animated_flip_counter: ^0.3.4
  carousel_slider: ^5.0.0
  flip_card: ^0.7.0
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1
  scratcher: ^2.5.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/prizes/
    - assets/background/
